### ISSUE TITLE
Using module with SSR from angular cli gives import error

### ISSUE THREAD

**Issue by jimmy-tfp** [nicky-lenaers/ngx-scroll-to#31]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Our SSR app is built using this guide: https://github.com/angular/angular-cli/wiki/stories-universal-rendering and works well. However if you npm install --save this module you get:

import xyz
^^^^^^
SyntaxError: Unexpected token import

when you run in on the server with "node server.js"

It works very well if we just build it in our app, Thanks!

## Expected behavior

It runs on the server.

## Minimal reproduction of the problem with instructions

Build a SSR app using the above guide. I could start over an make one if you want?

## What is the motivation / use case for changing the behavior?
Works on the server.

## Environment

<pre><code>
Angular version: 4.2.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  v6.11.2 
- Platform:  Mac

Others:

**Comment by nicky-lenaers** [comment]
Hi @jimmy-tfp, thank you for submitting your issue. I will be investigating this soon!

**Comment by jacobedawson** [comment]
@nicky-lenaers I just ran into this issue as well - the error only came up while building for SSR, same error as what @jimmy-tfp reported. 

Thanks for your work on the module but I would say until this issue is resolved you might want to remove the mention on the repo homepage that this module works with SSR.

**Comment by nicky-lenaers** [comment]
@jacobedawson @jimmy-tfp I'm working on this issue. Will be resolved soon!

**Comment by jacobedawson** [comment]
@nicky-lenaers thanks for your effort dude, in all other aspects it's a great module :)

**Comment by nicky-lenaers** [comment]
@jacobedawson @jimmy-tfp I did a full repo overhaul to enforce a package called `ng-packagr`. This module should package everything up properly. I just release `0.4.0-alpha.3`, which includes support for SSR builds. I tested it on my own repo and it works.

I'd like to get your feedback on whether it works or not.

Thanks, your feedback is much appreciated!

**Comment by jacobedawson** [comment]
Hi @nicky-lenaers - I just installed 0.4.0-alpha.3 and I got this error during compilation (no other changes made - just installed ngx-scroll-to, added imports in module.ts, set up the service from this repo):

```
 ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in C:/Users/Jake/Documents/GitHub/readreddit/node_modules/@nicky-lenaers/ngx-scroll-to/node_modules/@angular/core/core.d.ts, resolving symbol ScrollToModule in C:/Users/Jake/Documents/GitHub/readreddit/node_modules/@nicky-lenaers/ngx-scroll-to/ngx-scroll-to.d.ts, resolving symbol ScrollToModule in C:/Users/Jake/Documents/GitHub/readreddit/node_modules/@nicky-lenaers/ngx-scroll-to/ngx-scroll-to.d.ts
[0]     at positionalError (C:\Users\Jake\Documents\GitHub\readreddit\node_modules\@angular\compiler\bundles\compiler.umd.js:25266:35)
[0]     at simplifyInContext (C:\Users\Jake\Documents\GitHub\readreddit\node_modules\@angular\compiler\bundles\compiler.umd.js:25109:27)
[0]     at StaticReflector.simplify (C:\Users\Jake\Documents\GitHub\readreddit\node_modules\@angular\compiler\bundles\compiler.umd.js:25123:13)
[0]     at StaticReflector.annotations (C:\Users\Jake\Documents\GitHub\readreddit\node_modules\@angular\compiler\bundles\compiler.umd.js:24553:41)
[0]     at _getNgModuleMetadata (C:\Users\Jake\Documents\GitHub\readreddit\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
[0]     at _extractLazyRoutesFromStaticModule (C:\Users\Jake\Documents\GitHub\readreddit\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
[0]     at C:\Users\Jake\Documents\GitHub\readreddit\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
[0]     at Array.reduce (<anonymous>)
[0]     at _extractLazyRoutesFromStaticModule (C:\Users\Jake\Documents\GitHub\readreddit\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
[0]     at Object.listLazyRoutesOfModule (C:\Users\Jake\Documents\GitHub\readreddit\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
[0]     at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\Jake\Documents\GitHub\readreddit\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
[0]     at AotPlugin._getLazyRoutesFromNgtools (C:\Users\Jake\Documents\GitHub\readreddit\node_modules\@ngtools\webpack\src\plugin.js:207:44)
[0]     at _donePromise.Promise.resolve.then.then.then.then.then (C:\Users\Jake\Documents\GitHub\readreddit\node_modules\@ngtools\webpack\src\plugin.js:443:24)
[0]     at <anonymous>
[0]     at process._tickCallback (internal/process/next_tick.js:188:7)
[0]
[0] webpack: Failed to compile.
```

**Comment by nicky-lenaers** [comment]
@jacobedawson Thank you for reporting this. I came across [quiet a hot issue topic](https://github.com/angular/angular-cli/issues/3707) that references this issue. It seems there could be multiple factors that cause this error. Even outside of the scope of this module. The fact that I have a working example in a repo confirms that. 

I'd really like to help you with this. Do you mind setting up a small example repo or plunkr with your setup (or share the repo you already have if possible), so I'm able to properly figure out what causes this error?

Thanks in advance.

**Comment by jacobedawson** [comment]
@nicky-lenaers yo dude - sure thing, will have a look tomo morning (bedtime in berlin...zzz) and get back to you, cheers!

**Comment by nicky-lenaers** [comment]
Sure man, same thing in your neighbor Netherlands :-) let me know when you got something!

**Comment by nicky-lenaers** [comment]
@jacobedawson I've been doing research into this issue. It seems to not be related to this module specifically. My suggestion is to check your installed versions of Angular itself and go through topics that address your issue.

Thanks again for your feedback, this is much appreciated!

Closing this issue due to irrelevance to the module.
